package com.droidspiration.onlineartgallery.data.local

import androidx.room.Dao
import androidx.room.Database
import androidx.room.Entity
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.PrimaryKey
import androidx.room.Query
import androidx.room.RoomDatabase

@Entity(tableName = "object_ids")
data class ArtPiece(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,  // This will be auto-generated by Room
    val objectId: Int
)

@Dao
interface ArtGalleryRecordsDao {
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertRecords(objectIDs: List<ArtPiece>)

    @Query("SELECT objectId FROM object_ids ORDER BY RANDOM() LIMIT 1")
    suspend fun getRandomArtId(): Int
}

@Database(entities = [ArtPiece::class], version = 1)
internal abstract class ArtDatabase : RoomDatabase() {
    abstract fun artDao(): ArtGalleryRecordsDao
}